const USER_FREE = 0
const USER_WAITING = 1
const USER_RECONNECT = 2
const USER_GAMING = 200
const USER_LEAVING = -1

const ROOM_FREE = 0
const ROOM_WAITING = 1
const ROOM_GAMING = 2

const GAME_OVER = 4
const ROUND_FINISH = 3
const ROUND_START = 1

export {
  USER_FREE,
  USER_WAITING,
  USER_RECONNECT,
  USER_GAMING,
  USER_LEAVING,
  ROOM_FREE,
  ROOM_WAITING,
  ROOM_GAMING,
  GAME_OVER,
  ROUND_START,
  ROUND_FINISH
}